# configuration file for dotnet-releaser

[msbuild]
project = "dotnet.sln"

[github]
user = "LibreShark"
repo = "hammerhead"
version_prefix = "v"

[changelog]
publish = false

[nuget]
publish = false

[brew]
publish = false

[scoop]
publish = false
