//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreShark.Hammerhead {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("LibreShark.Hammerhead.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string GAMESHARK_LOGO_ASCII_ART_ANSI_TXT {
            get {
                return ResourceManager.GetString("GAMESHARK_LOGO_ASCII_ART_ANSI_TXT", resourceCulture);
            }
        }
        
        internal static string GAMESHARK_LOGO_ASCII_ART_PLAIN_TXT {
            get {
                return ResourceManager.GetString("GAMESHARK_LOGO_ASCII_ART_PLAIN_TXT", resourceCulture);
            }
        }
        
        internal static byte[] FIGLET_FONT_ANSI_REGULAR {
            get {
                object obj = ResourceManager.GetObject("FIGLET_FONT_ANSI_REGULAR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FIGLET_FONT_ANSI_SHADOW {
            get {
                object obj = ResourceManager.GetObject("FIGLET_FONT_ANSI_SHADOW", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FIGLET_FONT_BIG_MONEY_NW {
            get {
                object obj = ResourceManager.GetObject("FIGLET_FONT_BIG_MONEY_NW", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FIGLET_FONT_BIG {
            get {
                object obj = ResourceManager.GetObject("FIGLET_FONT_BIG", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FIGLET_FONT_COLOSSAL {
            get {
                object obj = ResourceManager.GetObject("FIGLET_FONT_COLOSSAL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FIGLET_FONT_CYBERLARGE {
            get {
                object obj = ResourceManager.GetObject("FIGLET_FONT_CYBERLARGE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FIGLET_FONT_CYBERMEDIUM {
            get {
                object obj = ResourceManager.GetObject("FIGLET_FONT_CYBERMEDIUM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FIGLET_FONT_DOOM {
            get {
                object obj = ResourceManager.GetObject("FIGLET_FONT_DOOM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FIGLET_FONT_NANCYJ_IMPROVED {
            get {
                object obj = ResourceManager.GetObject("FIGLET_FONT_NANCYJ_IMPROVED", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FIGLET_FONT_NANCYJ_UNDERLINED {
            get {
                object obj = ResourceManager.GetObject("FIGLET_FONT_NANCYJ_UNDERLINED", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FIGLET_FONT_NANCYJ {
            get {
                object obj = ResourceManager.GetObject("FIGLET_FONT_NANCYJ", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FIGLET_FONT_SLANT {
            get {
                object obj = ResourceManager.GetObject("FIGLET_FONT_SLANT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FIGLET_FONT_STANDARD {
            get {
                object obj = ResourceManager.GetObject("FIGLET_FONT_STANDARD", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FONT_PIXELMIX_STANDARD {
            get {
                object obj = ResourceManager.GetObject("FONT_PIXELMIX_STANDARD", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FONT_PIXELMIX_BOLD {
            get {
                object obj = ResourceManager.GetObject("FONT_PIXELMIX_BOLD", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
