//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreShark.Hammerhead {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("LibreShark.Hammerhead.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string GAMESHARK_LOGO_ASCII_ART_ANSI_TXT {
            get {
                return ResourceManager.GetString("GAMESHARK_LOGO_ASCII_ART_ANSI_TXT", resourceCulture);
            }
        }
        
        internal static string GAMESHARK_LOGO_ASCII_ART_PLAIN_TXT {
            get {
                return ResourceManager.GetString("GAMESHARK_LOGO_ASCII_ART_PLAIN_TXT", resourceCulture);
            }
        }
        
        internal static string LIBRESHARK_WORDMARK_ASCII_ART_PLAIN_TXT {
            get {
                return ResourceManager.GetString("LIBRESHARK_WORDMARK_ASCII_ART_PLAIN_TXT", resourceCulture);
            }
        }
        
        internal static string ASCII_BRAND_NAME_ACTION_REPLAY {
            get {
                return ResourceManager.GetString("ASCII_BRAND_NAME_ACTION_REPLAY", resourceCulture);
            }
        }
        
        internal static string ASCII_BRAND_NAME_BLAZE {
            get {
                return ResourceManager.GetString("ASCII_BRAND_NAME_BLAZE", resourceCulture);
            }
        }
        
        internal static string ASCII_BRAND_NAME_BRAINBOY {
            get {
                return ResourceManager.GetString("ASCII_BRAND_NAME_BRAINBOY", resourceCulture);
            }
        }
        
        internal static string ASCII_BRAND_NAME_CODE_BREAKER {
            get {
                return ResourceManager.GetString("ASCII_BRAND_NAME_CODE_BREAKER", resourceCulture);
            }
        }
        
        internal static string ASCII_BRAND_NAME_EQUALIZER {
            get {
                return ResourceManager.GetString("ASCII_BRAND_NAME_EQUALIZER", resourceCulture);
            }
        }
        
        internal static string ASCII_BRAND_NAME_GAME_BOOSTER {
            get {
                return ResourceManager.GetString("ASCII_BRAND_NAME_GAME_BOOSTER", resourceCulture);
            }
        }
        
        internal static string ASCII_BRAND_NAME_GAME_BUSTER {
            get {
                return ResourceManager.GetString("ASCII_BRAND_NAME_GAME_BUSTER", resourceCulture);
            }
        }
        
        internal static string ASCII_BRAND_NAME_GAME_GENIE {
            get {
                return ResourceManager.GetString("ASCII_BRAND_NAME_GAME_GENIE", resourceCulture);
            }
        }
        
        internal static string ASCII_BRAND_NAME_GAMESHARK {
            get {
                return ResourceManager.GetString("ASCII_BRAND_NAME_GAMESHARK", resourceCulture);
            }
        }
        
        internal static string ASCII_BRAND_NAME_GB_HUNTER {
            get {
                return ResourceManager.GetString("ASCII_BRAND_NAME_GB_HUNTER", resourceCulture);
            }
        }
        
        internal static string ASCII_BRAND_NAME_MONSTER_BRAIN {
            get {
                return ResourceManager.GetString("ASCII_BRAND_NAME_MONSTER_BRAIN", resourceCulture);
            }
        }
        
        internal static string ASCII_BRAND_NAME_SHARK_MX {
            get {
                return ResourceManager.GetString("ASCII_BRAND_NAME_SHARK_MX", resourceCulture);
            }
        }
        
        internal static string ASCII_BRAND_NAME_UNKNOWN {
            get {
                return ResourceManager.GetString("ASCII_BRAND_NAME_UNKNOWN", resourceCulture);
            }
        }
        
        internal static string ASCII_BRAND_NAME_XPLODER {
            get {
                return ResourceManager.GetString("ASCII_BRAND_NAME_XPLODER", resourceCulture);
            }
        }
        
        internal static string ASCII_BRAND_NAME_XPLORER {
            get {
                return ResourceManager.GetString("ASCII_BRAND_NAME_XPLORER", resourceCulture);
            }
        }
    }
}
