# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Publish

on:
  push:
    tags:
      - v1.**

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: dotnet/
      run: dotnet restore
    - name: Build, Test, Pack, and Publish compiled artifacts to a GitHub Release
      working-directory: dotnet/
      shell: bash
      run: |
        dotnet tool install --global GitVersion.Tool --version 5.*
        dotnet tool install --global dotnet-releaser
        dotnet-releaser publish --version "$(gitversion /output json /showvariable MajorMinorPatch)" --github-token "${{secrets.GITHUB_TOKEN}}" dotnet-releaser.toml
